import corpus from '@/legacy-content/legacy-clean.json';
import type { LegacyEntry, LegacyRegion } from './legacy-types';

export type { LegacyEntry, LegacyRegion } from './legacy-types';

/**
 * The cleaned legacy corpus (generated by scripts/build-legacy.ts from the
 * immutable WordPress export). It is the single source of truth for every
 * indexable URL on the site.
 */
export const legacyItems = corpus as LegacyEntry[];
export const legacyPages = legacyItems.filter((item) => item.kind === 'page');
export const legacyPosts = legacyItems
  .filter((item) => item.kind === 'post')
  .sort((a, b) => (b.date || '').localeCompare(a.date || ''));

/** Last change to any post: the honest `lastmod` for the /blog index. */
export const latestPostDate = legacyPosts.map((post) => post.modified || post.date || '').sort().at(-1) || undefined;

/** Paths that exist in the corpus but must never render (they 301 elsewhere). */
export const RETIRED_PATHS = new Set(['/home-3']);

const byPath = new Map(legacyItems.map((item) => [item.path, item]));

export function normalizeLegacyPath(path: string): string {
  return path.split(/[?#]/)[0].replace(/\/+$/, '') || '/';
}

export function getLegacyByPath(path: string): LegacyEntry | undefined {
  return byPath.get(normalizeLegacyPath(path));
}

/** Entries rendered by the catch-all route (everything except home & retired). */
export const routableItems = legacyItems.filter((item) => item.path !== '/' && !RETIRED_PATHS.has(item.path));

/** Every indexable page path ("/" for home, no trailing slash): the sitemap set, each with a markdown twin and a social card. */
export const indexablePaths = ['/', '/blog', ...routableItems.map((item) => item.path)];

export const REGION_LABELS: Record<LegacyRegion, string> = {
  bac: 'Miền Bắc',
  trung: 'Miền Trung',
  nam: 'Miền Nam',
  'tay-nguyen': 'Tây Nguyên',
  'quoc-te': 'Quốc tế & đa phương thức',
  'loai-hang': 'Theo loại hàng',
};

export const ROUTE_REGIONS: LegacyRegion[] = ['bac', 'trung', 'nam', 'tay-nguyen', 'quoc-te'];

export const routeItems = legacyItems
  .filter((item) => item.template === 'route' || (item.template === 'cargo' && item.region === 'quoc-te'))
  .sort((a, b) => a.label.localeCompare(b.label, 'vi'));

export const cargoItems = legacyItems.filter((item) => item.template === 'cargo' && item.region === 'loai-hang');
export const truckItems = legacyItems.filter((item) => item.template === 'truck');

export function routesByRegion(): Array<{ region: LegacyRegion; label: string; items: LegacyEntry[] }> {
  return ROUTE_REGIONS.map((region) => ({
    region,
    label: REGION_LABELS[region],
    items: routeItems.filter((item) => item.region === region),
  })).filter((group) => group.items.length > 0);
}

/** Same-region routes first, then other popular routes — strong internal linking. */
export function relatedRoutes(item: LegacyEntry, limit = 8): LegacyEntry[] {
  const sameRegion = routeItems.filter((candidate) => candidate.path !== item.path && candidate.region === item.region);
  const others = routeItems.filter((candidate) => candidate.path !== item.path && candidate.region !== item.region);
  return [...sameRegion, ...others].slice(0, limit);
}

export function relatedPosts(item: LegacyEntry, limit = 3): LegacyEntry[] {
  return legacyPosts.filter((post) => post.path !== item.path).slice(0, limit);
}
