import corpus from '@/legacy-content/legacy-clean.json';
import { ROUTE_COORDINATES } from '@/content/route-coordinates';
import type { LegacyEntry, LegacyRegion } from './legacy-types';
import { POPULAR_ROUTES } from './marketing';

export type { LegacyEntry, LegacyRegion } from './legacy-types';

/**
 * The cleaned legacy corpus (generated by scripts/build-legacy.ts from the
 * immutable WordPress export). It is the single source of truth for every
 * indexable URL on the site.
 */
export const legacyItems = corpus as LegacyEntry[];
export const legacyPages = legacyItems.filter((item) => item.kind === 'page');
export const legacyPosts = legacyItems
  .filter((item) => item.kind === 'post')
  .sort((a, b) => (b.date || '').localeCompare(a.date || ''));

/** Last change to any post: the honest `lastmod` for the /blog index. */
export const latestPostDate = legacyPosts.map((post) => post.modified || post.date || '').sort().at(-1) || undefined;

/** Paths that exist in the corpus but must never render (they 301 elsewhere). */
export const RETIRED_PATHS = new Set(['/home-3']);

const byPath = new Map(legacyItems.map((item) => [item.path, item]));

export function normalizeLegacyPath(path: string): string {
  return path.split(/[?#]/)[0].replace(/\/+$/, '') || '/';
}

export function getLegacyByPath(path: string): LegacyEntry | undefined {
  return byPath.get(normalizeLegacyPath(path));
}

/**
 * Home page FAQ (page and markdown twin): the customer questions of the shipping hub (transit time,
 * price, cargo, door-to-door). The /faq page holds encyclopedic definitions ("Vận tải là gì?").
 */
export function homeFaq() {
  return getLegacyByPath('/van-chuyen-hang-hoa')?.faq ?? [];
}

/** Entries rendered by the catch-all route (everything except home & retired). */
export const routableItems = legacyItems.filter((item) => item.path !== '/' && !RETIRED_PATHS.has(item.path));

/** Every indexable page path ("/" for home, no trailing slash): the sitemap set, each with a markdown twin and a social card. */
export const indexablePaths = ['/', '/blog', ...routableItems.map((item) => item.path)];

export const REGION_LABELS: Record<LegacyRegion, string> = {
  bac: 'Miền Bắc',
  trung: 'Miền Trung',
  nam: 'Miền Nam',
  'tay-nguyen': 'Tây Nguyên',
  'quoc-te': 'Quốc tế',
  'loai-hang': 'Loại hàng & phương thức',
};

export const ROUTE_REGIONS: LegacyRegion[] = ['bac', 'trung', 'nam', 'tay-nguyen', 'quoc-te'];

export const routeItems = legacyItems
  .filter((item) => item.template === 'route' || (item.template === 'cargo' && item.region === 'quoc-te'))
  .sort((a, b) => a.label.localeCompare(b.label, 'vi'));

export const cargoItems = legacyItems.filter((item) => item.template === 'cargo' && item.region === 'loai-hang');
export const truckItems = legacyItems.filter((item) => item.template === 'truck');

export function routesByRegion(): Array<{ region: LegacyRegion; label: string; items: LegacyEntry[] }> {
  return ROUTE_REGIONS.map((region) => ({
    region,
    label: REGION_LABELS[region],
    items: routeItems.filter((item) => item.region === region),
  })).filter((group) => group.items.length > 0);
}

const byPaths = (paths: string[]) => paths.map((path) => byPath.get(path)).filter((entry): entry is LegacyEntry => Boolean(entry));
const popularRoutes = byPaths(POPULAR_ROUTES.map((route) => normalizeLegacyPath(route.href)));

/** Stable small hash so "rotate the equally good candidates" is deterministic per page (static HTML must not change between builds). */
function seedOf(path: string): number {
  let hash = 0;
  for (const char of path) hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
  return hash;
}
const rotate = <T,>(list: T[], seed: number) => (list.length ? [...list.slice(seed % list.length), ...list.slice(0, seed % list.length)] : list);

/** The route page and the truck rental page for the same city link each other first. */
export const CITY_TRUCK_PAGES: Record<string, string> = {
  '/van-chuyen-hang-hoa/ha-noi': '/thue-xe-tai/ha-noi',
  '/van-chuyen-hang-hoa/da-nang': '/thue-xe-tai/da-nang',
  '/van-chuyen-hang-hoa/tphcm': '/thue-xe-tai/hcm',
};

const RELATED_LIMIT = 8;
/** Nearest destinations listed on each route page; the remaining slots balance links and popular routes. */
const NEAREST_ROUTES = 6;
/** Every route with coordinates is listed on at least this many other route pages. */
const MIN_ROUTE_INLINKS = 5;

/** Great-circle distance in km between two [lat, lon] points. */
function distanceKm([lat1, lon1]: readonly [number, number], [lat2, lon2]: readonly [number, number]) {
  const rad = Math.PI / 180;
  const h = Math.sin(((lat2 - lat1) * rad) / 2) ** 2 + Math.cos(lat1 * rad) * Math.cos(lat2 * rad) * Math.sin(((lon2 - lon1) * rad) / 2) ** 2;
  return 12742 * Math.asin(Math.sqrt(h));
}

/**
 * Geographic neighbours for every route that has coordinates: its six nearest destinations, then
 * routes that would otherwise be listed on fewer than five pages are added to the lists of their
 * own nearest pages, so remote provinces (Cà Mau, Cao Bằng) still receive links. Deterministic, so
 * the static HTML does not change between builds.
 */
const geoNeighbours: Map<string, LegacyEntry[]> = (() => {
  // Laos and Cambodia stay in their small international group with the sea and air pages.
  const located = routeItems.filter((item) => item.region !== 'quoc-te' && ROUTE_COORDINATES[item.slug]);
  const nearest = new Map(located.map((item) => [item.path, located
    .filter((other) => other !== item)
    .map((other) => ({ other, km: distanceKm(ROUTE_COORDINATES[item.slug], ROUTE_COORDINATES[other.slug]) }))
    .sort((a, b) => a.km - b.km || a.other.path.localeCompare(b.other.path))
    .map(({ other }) => other)]));
  const lists = new Map(located.map((item) => [item.path, nearest.get(item.path)!.slice(0, NEAREST_ROUTES)]));
  const inlinks = (item: LegacyEntry) => located.filter((page) => lists.get(page.path)!.includes(item)).length;
  for (const item of located) {
    for (const page of nearest.get(item.path)!) {
      if (inlinks(item) >= MIN_ROUTE_INLINKS) break;
      const list = lists.get(page.path)!;
      if (list.length < RELATED_LIMIT - 1 && !list.includes(item)) list.push(item);
    }
  }
  // Laos and Cambodia are listed on the three domestic routes nearest to them (border provinces).
  for (const abroad of routeItems.filter((item) => item.region === 'quoc-te' && ROUTE_COORDINATES[item.slug])) {
    located
      .map((page) => ({ page, km: distanceKm(ROUTE_COORDINATES[abroad.slug], ROUTE_COORDINATES[page.slug]) }))
      .sort((a, b) => a.km - b.km || a.page.path.localeCompare(b.page.path))
      .slice(0, 3)
      .forEach(({ page }) => lists.get(page.path)!.push(abroad));
  }
  return lists;
})();

/**
 * Links to other routes for a route or cargo page. Routes list their nearest destinations
 * (ROUTE_COORDINATES), with the same city's truck rental page first; routes without coordinates
 * link their alphabetical neighbours within the region, and cargo pages link the other cargo
 * services. Popular routes fill the remainder.
 */
export function relatedRoutes(item: LegacyEntry, limit = RELATED_LIMIT): LegacyEntry[] {
  const picked: LegacyEntry[] = [];
  const add = (candidate?: LegacyEntry) => {
    if (candidate && candidate.path !== item.path && !picked.includes(candidate) && picked.length < limit) picked.push(candidate);
  };
  const neighbours = geoNeighbours.get(item.path);
  if (CITY_TRUCK_PAGES[item.path]) add(byPath.get(CITY_TRUCK_PAGES[item.path]));
  // A region page (/tay-nguyen) lists every route of its region before any neighbour.
  if (item.slug === item.region) routeItems.filter((candidate) => candidate.region === item.region).forEach((candidate) => add(candidate));
  if (item.region === 'loai-hang') {
    cargoItems.forEach((candidate) => add(candidate));
  } else if (neighbours) {
    neighbours.forEach((candidate) => add(candidate));
  } else {
    const peers = routeItems.filter((candidate) => candidate.region === item.region);
    const index = peers.indexOf(item);
    for (let step = 1; index >= 0 && step < peers.length; step++) {
      add(peers[(index + step) % peers.length]);
      add(peers[(index - step + peers.length) % peers.length]);
    }
  }
  popularRoutes.forEach((candidate) => add(candidate));
  return picked;
}

/** The truck page's own city route first, then that route's nearest destinations. */
export function truckRelatedRoutes(item: LegacyEntry, limit = RELATED_LIMIT): LegacyEntry[] {
  const routePath = Object.keys(CITY_TRUCK_PAGES).find((path) => CITY_TRUCK_PAGES[path] === item.path);
  const route = routePath ? byPath.get(routePath) : undefined;
  if (!route) return [];
  return [route, ...relatedRoutes(route, limit).filter((entry) => entry.template === 'route')].slice(0, limit);
}

const SERVICE_TEMPLATES = new Set(['route', 'route-hub', 'cargo', 'truck', 'truck-hub']);
/** Guides listed on a service page: two, so the guides do not outweigh the service pages around them. */
export const SERVICE_RELATED_POSTS = 2;

/** What each guide is about; pages and guides sharing a topic link to each other. */
type Topic = 'truck' | 'cargo' | 'dangerous' | 'route' | 'business' | 'company';
const POST_TOPICS: Record<string, Topic[]> = {
  '/blog/bien-bao-cam-xe-tai-va-muc-phat': ['truck', 'route'],
  '/blog/can-tim-doi-tac-van-chuyen-hang-hoa': ['business'],
  '/blog/dich-y-nghia-bien-so-xe-theo-phong-thuy-khoa-hoc': ['business'],
  '/blog/giay-to-van-chuyen-hang-hoa': ['business', 'cargo', 'route'],
  '/blog/hang-hoa-thuong-gap-trong-nganh-van-tai': ['cargo', 'route'],
  '/blog/kich-thuoc-thung-xe-tai-trong-van-tai-hang-hoa': ['truck', 'cargo'],
  '/blog/quy-dinh-van-chuyen-hang-hoa-nguy-hiem': ['dangerous', 'cargo'],
  '/blog/van-chuyen-hang-hoa-nguy-hiem': ['dangerous', 'cargo'],
  '/blog/van-tai-phuong-vy-duoc-uu-tien-hoat-dong-tren-luong-xanh': ['company'],
};

function topicsOf(item: LegacyEntry): Topic[] {
  if (item.kind === 'post') return POST_TOPICS[item.path] ?? [];
  if (item.template === 'home') return ['route', 'truck', 'cargo'];
  if (item.template === 'truck' || item.template === 'truck-hub') return ['truck'];
  if (item.path === '/van-chuyen-hang-hoa/dau-nhot') return ['dangerous', 'cargo'];
  if (item.template === 'cargo') return ['cargo'];
  if (item.template === 'route' || item.template === 'route-hub') return ['route'];
  if (['/gioi-thieu', '/thu-ngo', '/tuyen-dung'].includes(item.path)) return ['company', 'business'];
  return ['business', 'route'];
}

/**
 * Guides that share the most topics with the page, newest first within a tier.
 * Equally relevant guides are rotated per page so the links spread across all of
 * them instead of every page pointing at the same three posts.
 */
export function relatedPosts(item: LegacyEntry, limit = 3): LegacyEntry[] {
  const topics = new Set(topicsOf(item));
  // Service pages only show guides on their topic; other pages may fill with the rest.
  const onTopicOnly = SERVICE_TEMPLATES.has(item.template);
  const scored = legacyPosts
    .filter((post) => post.path !== item.path)
    .map((post) => ({ post, score: topicsOf(post).filter((topic) => topics.has(topic)).length }))
    .filter((entry) => !onTopicOnly || entry.score > 0);
  const tiers = [...new Set(scored.map((entry) => entry.score))].sort((a, b) => b - a);
  const seed = seedOf(item.path);
  return tiers.flatMap((score) => rotate(scored.filter((entry) => entry.score === score).map((entry) => entry.post), seed)).slice(0, limit);
}

/** Service pages a guide's readers are most likely to need next (guide → money page links). */
const TOPIC_SERVICES: Record<Topic, string[]> = {
  truck: ['/thue-xe-tai', '/thue-xe-tai/hcm', '/thue-xe-tai/ha-noi', '/thue-xe-tai/da-nang'],
  dangerous: ['/van-chuyen-hang-hoa/dau-nhot', '/van-chuyen-hang-hoa/sieu-truong-sieu-trong'],
  cargo: ['/van-chuyen-hang-hoa/may-moc-thiet-bi', '/van-chuyen-hang-hoa/xe-may', '/van-chuyen-hang-hoa/sieu-truong-sieu-trong'],
  route: ['/van-chuyen-hang-hoa', '/van-chuyen-hang-hoa/ha-noi', '/van-chuyen-hang-hoa/da-nang'],
  business: ['/van-chuyen-hang-hoa', '/thue-xe-tai'],
  company: ['/gioi-thieu', '/van-chuyen-hang-hoa'],
};

/** Topic services first; the main route pages fill guides whose topics name only one or two. */
/** Guides about specific cities link those cities' route pages (the truck-ban guide covers these four). */
const POST_SERVICES: Record<string, string[]> = {
  '/blog/bien-bao-cam-xe-tai-va-muc-phat': ['/van-chuyen-hang-hoa/tphcm', '/van-chuyen-hang-hoa/ha-noi', '/van-chuyen-hang-hoa/da-nang', '/van-chuyen-hang-hoa/nha-trang'],
};

export function relatedServices(item: LegacyEntry, limit = 4): LegacyEntry[] {
  const paths = [...new Set([...(POST_SERVICES[item.path] ?? []), ...topicsOf(item).flatMap((topic) => TOPIC_SERVICES[topic]), ...TOPIC_SERVICES.route])];
  return byPaths(paths).slice(0, limit);
}
