/**
 * Where each route page's destination belongs since the provincial merger of 12/06/2025 (Nghị quyết
 * 202/2025/QH15), shown under the route hero and in its markdown twin. Keyed by page slug; destinations
 * whose province did not change have no entry. Source: the 34 provincial units published on
 * xaydungchinhsach.chinhphu.vn (checked 10/10/2026, see plans/reports/legal-merger-research-261010-1505.md).
 */
export const PROVINCE_MERGERS: Record<string, string> = {
  'an-giang': 'Từ 12/6/2025, tỉnh An Giang mới gồm An Giang và Kiên Giang cũ.',
  'bac-giang': 'Từ 12/6/2025, Bắc Giang thuộc tỉnh Bắc Ninh.',
  'bac-kan': 'Từ 12/6/2025, Bắc Kạn thuộc tỉnh Thái Nguyên.',
  'bac-lieu': 'Từ 12/6/2025, Bạc Liêu thuộc tỉnh Cà Mau.',
  'bac-ninh': 'Từ 12/6/2025, tỉnh Bắc Ninh mới gồm Bắc Ninh và Bắc Giang cũ.',
  'ben-tre': 'Từ 12/6/2025, Bến Tre thuộc tỉnh Vĩnh Long.',
  'binh-dinh': 'Từ 12/6/2025, Bình Định thuộc tỉnh Gia Lai.',
  'binh-duong': 'Từ 12/6/2025, Bình Dương thuộc thành phố Hồ Chí Minh.',
  'binh-phuoc': 'Từ 12/6/2025, Bình Phước thuộc tỉnh Đồng Nai.',
  'binh-thuan': 'Từ 12/6/2025, Bình Thuận thuộc tỉnh Lâm Đồng.',
  'ca-mau': 'Từ 12/6/2025, tỉnh Cà Mau mới gồm Cà Mau và Bạc Liêu cũ.',
  'can-tho': 'Từ 12/6/2025, thành phố Cần Thơ mới gồm Cần Thơ, Sóc Trăng và Hậu Giang cũ.',
  'chanh-xe-chuyen-hang-di-buon-me-thuot': 'Từ 12/6/2025, Buôn Ma Thuột thuộc tỉnh Đắk Lắk mới (gồm Đắk Lắk và Phú Yên cũ). Thành phố Buôn Ma Thuột cũ nay là các phường, trong đó có phường Buôn Ma Thuột.',
  'chanh-xe-phu-quoc': 'Từ 12/6/2025, Phú Quốc thuộc tỉnh An Giang. Phú Quốc nay là đặc khu Phú Quốc.',
  'da-lat-lam-dong': 'Từ 12/6/2025, tỉnh Lâm Đồng mới gồm Lâm Đồng, Đắk Nông và Bình Thuận cũ. Đà Lạt cũ nay là các phường Xuân Hương - Đà Lạt, Cam Ly - Đà Lạt, Lâm Viên - Đà Lạt, Xuân Trường - Đà Lạt, Lang Biang - Đà Lạt.',
  'da-nang': 'Từ 12/6/2025, thành phố Đà Nẵng mới gồm Đà Nẵng và Quảng Nam cũ.',
  'dak-lak': 'Từ 12/6/2025, tỉnh Đắk Lắk mới gồm Đắk Lắk và Phú Yên cũ.',
  'dak-nong': 'Từ 12/6/2025, Đắk Nông thuộc tỉnh Lâm Đồng.',
  'dong-nai': 'Từ 12/6/2025, tỉnh Đồng Nai mới gồm Đồng Nai và Bình Phước cũ.',
  'dong-thap': 'Từ 12/6/2025, tỉnh Đồng Tháp mới gồm Đồng Tháp và Tiền Giang cũ.',
  'gia-lai': 'Từ 12/6/2025, tỉnh Gia Lai mới gồm Gia Lai và Bình Định cũ.',
  'hai-duong': 'Từ 12/6/2025, Hải Dương thuộc thành phố Hải Phòng.',
  'hai-phong': 'Từ 12/6/2025, thành phố Hải Phòng mới gồm Hải Phòng và Hải Dương cũ.',
  'hau-giang': 'Từ 12/6/2025, Hậu Giang thuộc thành phố Cần Thơ.',
  'hoa-binh': 'Từ 12/6/2025, Hòa Bình thuộc tỉnh Phú Thọ.',
  'hung-yen': 'Từ 12/6/2025, tỉnh Hưng Yên mới gồm Hưng Yên và Thái Bình cũ.',
  kontum: 'Từ 12/6/2025, Kon Tum thuộc tỉnh Quảng Ngãi.',
  'lao-cai': 'Từ 12/6/2025, tỉnh Lào Cai mới gồm Lào Cai và Yên Bái cũ.',
  'long-an': 'Từ 12/6/2025, Long An thuộc tỉnh Tây Ninh.',
  'nam-dinh': 'Từ 12/6/2025, Nam Định thuộc tỉnh Ninh Bình.',
  'nha-trang': 'Từ 12/6/2025, Nha Trang thuộc tỉnh Khánh Hòa mới (gồm Khánh Hòa và Ninh Thuận cũ). Nha Trang cũ nay là các phường Nha Trang, Bắc Nha Trang, Tây Nha Trang, Nam Nha Trang.',
  'ninh-binh': 'Từ 12/6/2025, tỉnh Ninh Bình mới gồm Ninh Bình, Hà Nam và Nam Định cũ.',
  'ninh-thuan': 'Từ 12/6/2025, Ninh Thuận thuộc tỉnh Khánh Hòa.',
  'phan-thiet': 'Từ 12/6/2025, Phan Thiết thuộc tỉnh Lâm Đồng. Phần trung tâm Phan Thiết cũ nay là phường Phan Thiết.',
  'phu-tho': 'Từ 12/6/2025, tỉnh Phú Thọ mới gồm Phú Thọ, Vĩnh Phúc và Hòa Bình cũ.',
  'phu-yen': 'Từ 12/6/2025, Phú Yên thuộc tỉnh Đắk Lắk.',
  'quang-binh': 'Từ 12/6/2025, Quảng Bình thuộc tỉnh Quảng Trị.',
  'quang-nam': 'Từ 12/6/2025, Quảng Nam thuộc thành phố Đà Nẵng.',
  'quang-ngai': 'Từ 12/6/2025, tỉnh Quảng Ngãi mới gồm Quảng Ngãi và Kon Tum cũ.',
  'quang-tri': 'Từ 12/6/2025, tỉnh Quảng Trị mới gồm Quảng Trị và Quảng Bình cũ.',
  'soc-trang': 'Từ 12/6/2025, Sóc Trăng thuộc thành phố Cần Thơ.',
  'tay-nguyen': 'Từ 12/6/2025, năm tỉnh Tây Nguyên cũ thuộc 4 tỉnh: Gia Lai, Đắk Lắk, Lâm Đồng (gồm Đắk Nông cũ) và Quảng Ngãi (gồm Kon Tum cũ).',
  'tay-ninh': 'Từ 12/6/2025, tỉnh Tây Ninh mới gồm Tây Ninh và Long An cũ.',
  'thai-binh': 'Từ 12/6/2025, Thái Bình thuộc tỉnh Hưng Yên.',
  'thai-nguyen': 'Từ 12/6/2025, tỉnh Thái Nguyên mới gồm Thái Nguyên và Bắc Kạn cũ.',
  'tien-giang': 'Từ 12/6/2025, Tiền Giang thuộc tỉnh Đồng Tháp.',
  tphcm: 'Từ 12/6/2025, thành phố Hồ Chí Minh mới gồm TP.HCM, Bình Dương và Bà Rịa - Vũng Tàu cũ.',
  'tra-vinh': 'Từ 12/6/2025, Trà Vinh thuộc tỉnh Vĩnh Long.',
  'vinh-long': 'Từ 12/6/2025, tỉnh Vĩnh Long mới gồm Vĩnh Long, Bến Tre và Trà Vinh cũ.',
  'vinh-phuc': 'Từ 12/6/2025, Vĩnh Phúc thuộc tỉnh Phú Thọ.',
  'vung-tau': 'Từ 12/6/2025, Vũng Tàu thuộc thành phố Hồ Chí Minh. Vũng Tàu cũ nay là các phường Vũng Tàu, Tam Thắng, Rạch Dừa, Phước Thắng và các phường khác.',
  'yen-bai': 'Từ 12/6/2025, Yên Bái thuộc tỉnh Lào Cai.',
};
